business_time:
  beginning_of_workday: 9:30 am
  end_of_workday: 6:30 pm
  holidays:
    - January 1st, 2017
    - January 2nd, 2017
    - January 9th, 2017
    - February 11th, 2017
    - March 20th, 2017
    - April 29th, 2017
    - May 3rd, 2017
    - May 4th, 2017
    - May 5th, 2017
    - July 17th, 2017
    - August 11th, 2017
    - September 18th, 2017
    - September 23rd, 2017
    - October 9th, 2017
    - November 3rd, 2017
    - November 23rd, 2017
    - December 23rd, 2017
    - December 31st, 2017
  work_week:
    - mon
    - tue
    - wed
    - thu
    - fri
